Technical Specification:

1. Function Module Name: CNV_2010C_FILL_BAPIRET2

  a. Import Parameters:
     - TYPE (Type: BAPIRETURN-TYPE)
     - CL (Type: SY-MSGID)
     - NUMBER (Type: SY-MSGNO)
     - PAR1 (Type: SY-MSGV1, Default: SPACE)
     - PAR2 (Type: SY-MSGV2, Default: SPACE)
     - PAR3 (Type: SY-MSGV3, Default: SPACE)
     - PAR4 (Type: SY-MSGV4, Default: SPACE)
     - LOG_NO (Type: BAPIRETURN-LOG_NO, Default: SPACE)
     - LOG_MSG_NO (Type: BAPIRETURN-LOG_MSG_NO, Default: SPACE)
     - PARAMETER (Type: BAPIRET2-PARAMETER, Default: SPACE)
     - ROW (Type: BAPIRET2-ROW, Default: 0)
     - FIELD (Type: BAPIRET2-FIELD, Default: SPACE)

  b. Export Parameters:
     - RETURN (Type: BAPIRET2 structure)

2. Function Module Name: CNV_2010C_GET_DOMAIN_FIXED_VAL

  a. Import Parameters:
     - IV_DOMNAME (Type: DOMNAME)

  b. Export Parameters:
     - EV_DOMNAME (Type: DOMNAME)

  c. Table Parameters:
     - ET_DOMAIN_FIXED_VAL (Type: CNV_2010C_T_DOMAIN_FIXED_VALUE, Optional)
     - RETURN (Type: BAPIRET2 structure, Optional)

Functionality:

1. The first function module CNV_2010C_FILL_BAPIRET2 fills the BAPIRET2 structure, which is used to return messages to the calling program.
2. The second function module CNV_2010C_GET_DOMAIN_FIXED_VAL retrieves and returns domain fixed values from the database based on the provided domain name, IV_DOMNAME. The exported fixed values are populated in the ET_DOMAIN_FIXED_VAL internal table.CLASS ZCL_TECHNICAL_SPEC DEFINITION
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
    TYPES: BEGIN OF TY_BAPIRET2,
             TYPE TYPE BAPIRETURN-TYPE,
             CL TYPE SY-MSGID,
             NUMBER TYPE SY-MSGNO,
             PAR1 TYPE SY-MSGV1,
             PAR2 TYPE SY-MSGV2,
             PAR3 TYPE SY-MSGV3,
             PAR4 TYPE SY-MSGV4,
             LOG_NO TYPE BAPIRETURN-LOG_NO,
             LOG_MSG_NO TYPE BAPIRETURN-LOG_MSG_NO,
             PARAMETER TYPE BAPIRET2-PARAMETER,
             ROW TYPE BAPIRET2-ROW,
             FIELD TYPE BAPIRET2-FIELD,
           END OF TY_BAPIRET2.

    TYPES: BEGIN OF TY_CNV_2010C_T_DOMAIN_FIXED_VALUE,
             VALUE TYPE CHAR255,
           END OF TY_CNV_2010C_T_DOMAIN_FIXED_VALUE.

    METHODS CNV_2010C_FILL_BAPIRET2
      IMPORTING
        !IV_TYPE TYPE BAPIRETURN-TYPE
        !IV_CL TYPE SY-MSGID
        !IV_NUMBER TYPE SY-MSGNO
        !IV_PAR1 TYPE SY-MSGV1 DEFAULT SPACE
        !IV_PAR2 TYPE SY-MSGV2 DEFAULT SPACE
        !IV_PAR3 TYPE SY-MSGV3 DEFAULT SPACE
        !IV_PAR4 TYPE SY-MSGV4 DEFAULT SPACE
        !IV_LOG_NO TYPE BAPIRETURN-LOG_NO DEFAULT SPACE
        !IV_LOG_MSG_NO TYPE BAPIRETURN-LOG_MSG_NO DEFAULT SPACE
        !IV_PARAMETER TYPE BAPIRET2-PARAMETER DEFAULT SPACE
        !IV_ROW TYPE BAPIRET2-ROW DEFAULT 0
        !IV_FIELD TYPE BAPIRET2-FIELD DEFAULT SPACE
      EXPORTING
        !ES_RETURN TYPE TY_BAPIRET2.

    METHODS CNV_2010C_GET_DOMAIN_FIXED_VAL
      IMPORTING
        !IV_DOMNAME TYPE DOMNAME
      EXPORTING
        !EV_DOMNAME TYPE DOMNAME
      TABLES
        ET_DOMAIN_FIXED_VAL TYPE TABLE_OF TY_CNV_2010C_T_DOMAIN_FIXED_VALUE OPTIONAL
        ES_RETURN TYPE TY_BAPIRET2 OPTIONAL.

ENDCLASS.

CLASS ZCL_TECHNICAL_SPEC IMPLEMENTATION.

  METHOD CNV_2010C_FILL_BAPIRET2.
    DATA: LS_BAPIRET2 TYPE TY_BAPIRET2.

    LS_BAPIRET2-TYPE = IV_TYPE.
    LS_BAPIRET2-CL = IV_CL.
    LS_BAPIRET2-NUMBER = IV_NUMBER.
    LS_BAPIRET2-PAR1 = IV_PAR1.
    LS_BAPIRET2-PAR2 = IV_PAR2.
    LS_BAPIRET2-PAR3 = IV_PAR3.
    LS_BAPIRET2-PAR4 = IV_PAR4.
    LS_BAPIRET2-LOG_NO = IV_LOG_NO.
    LS_BAPIRET2-LOG_MSG_NO = IV_LOG_MSG_NO.
    LS_BAPIRET2-PARAMETER = IV_PARAMETER.
    LS_BAPIRET2-ROW = IV_ROW.
    LS_BAPIRET2-FIELD = IV_FIELD.

    ES_RETURN = LS_BAPIRET2.
  ENDMETHOD.

  METHOD CNV_2010C_GET_DOMAIN_FIXED_VAL.
    SELECT FIXED_VALUES
      INTO TABLE ET_DOMAIN_FIXED_VAL
      FROM DD07L
      WHERE DOMNAME = IV_DOMNAME.

    RETURN-EV_DOMNAME = IV_DOMNAME.
  ENDMETHOD.

ENDCLASS.